name: OpenDP SmartNoise Gate

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install opendp-smartnoise
      run: |
        pip install ./sdk
        pip install -r tests/requirements.txt
    - name: Create a wheel
      run: |
        source activate wnoise
        pip install --upgrade setuptools wheel twine
        cd ./python
        python setup.py bdist_wheel
        cd ..
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 sdk/opendp/smartnoise/sql/dpsu.py -v
        flake8 sdk/opendp/smartnoise/reader/ -v
        flake8 sdk/opendp/smartnoise/synthesizers/ -v
    - name: Test with pytest
      run: |
        conda install pytest
        pytest tests/sdk -s -m "not torch"  --junitxml=./TEST-TEST.xml
        
